export const enum ErrorCode {
    CONFIG_INVALID = 'CONFIG_INVALID',
    EMULATOR_NOT_FOUND = 'EMULATOR_NOT_FOUND',
    ASSEMBLER_NOT_FOUND = 'ASSEMBLER_NOT_FOUND',
    EXECUTABLE_NOT_FOUND = 'EXECUTABLE_NOT_FOUND',
    EMULATOR_LAUNCH_FAILED = 'EMULATOR_LAUNCH_FAILED',
    IPC_CONNECTION_REFUSED = 'IPC_CONNECTION_REFUSED',
    IPC_TIMEOUT = 'IPC_TIMEOUT',
    IPC_DECODE_ERROR = 'IPC_DECODE_ERROR',
}
